[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
remappings = [
    "@balancer-labs/=node_modules/@balancer-labs/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@pancakeswap/=node_modules/@pancakeswap/",
    "@uniswap/=node_modules/@uniswap/",
    "base64-sol/=node_modules/base64-sol/",
    "hardhat/=node_modules/hardhat/",
]
optimizer = true
optimizer_runs = 200
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
